name: dare-sql-deploy-template

on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        type: string
      artifactName:
        description: 'The name of the artifact to download'
        required: true
        type: string
      dacpacName:
        description: 'The name of the dacpac file'  
        required: true
        type: string

      # server:
      #   required: true
      # database:
      #   required: true
      # username:
      #   required: true
      # password:
      #   required: true
    
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_SQL_CONNECTION_STRING:
        required: true

permissions:
  id-token: write
  contents: read
  
jobs:
  deploy:
    runs-on: windows-latest #[Self-hosted, windows-latest, cac]
    environment: ${{ inputs.environment }}
    steps:
      - name: Download Dacpac
        uses: actions/download-artifact@v2.1.1
        with:
          name: ${{ inputs.artifactName }}
          path: ${{ github.workspace }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: List
        run: ls -R ${{ github.workspace }}

      # - name: Deploy dacpac
      #   uses: Azure/sql-action@v2.2
      #   with:
      #     server-name: ${{ secrets.SQL_SERVER }}
      #     database-name: ${{ secrets.SQL_DATABASE }}
      #     auth: 'service-principal'
      #     dacpac-package: ${{ github.workspace }}/${{ inputs.dacpacName }}
      #     additional-arguments: '/p:BlockOnPossibleDataLoss=false'
       # secrets:
       #    AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
       #    AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
       #    AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          

      - name: Deploy dacpac
        uses: Azure/sql-action@v2.2
        with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: ${{ github.workspace }}/${{ inputs.dacpacName }}
          #additional-arguments: '/p:BlockOnPossibleDataLoss=false'
          action: 'Publish'
